//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionNavette.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class abonnement
    {
        public int Id { get; set; }


        [Display(Name = "Nombre de mois")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        public int nbrMois { get; set; }
        public int id_client { get; set; }
        public int id_trajet { get; set; }
    
        public virtual client client { get; set; }
        public virtual trajet trajet { get; set; }
    }
}
