//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionNavette.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using CompareAttribute = System.ComponentModel.DataAnnotations.CompareAttribute;

    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.abonnements = new HashSet<abonnement>();
            this.societes = new HashSet<societe>();
            this.demandes = new HashSet<demande>();
            this.admins = new HashSet<admin>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Nom")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        public string nom { get; set; }

        [Display(Name = "Prenom")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        public string prenom { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        public string email { get; set; }

        [Display(Name = "Telephone")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        public decimal telephone { get; set; }

        [Display(Name = "Mot de passe")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        public string password { get; set; }


        [Display(Name = "Confirmer Mot de passe")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        [Compare("password", ErrorMessage = "les mots de passe ne sont pas identiques")]
        public string confirmPassword { get; set; }

        public bool isSociete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abonnement> abonnements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<societe> societes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<demande> demandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin> admins { get; set; }
    }
}
