//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionNavette.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestionNavetteEntities2 : DbContext
    {
        public gestionNavetteEntities2()
            : base("name=gestionNavetteEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abonnement> abonnements { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<societe> societes { get; set; }
        public virtual DbSet<trajet> trajets { get; set; }
        public virtual DbSet<transport> transports { get; set; }
        public virtual DbSet<demande> demandes { get; set; }
        public virtual DbSet<admin> admins { get; set; }
    }
}
