//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionNavette.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class societe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public societe()
        {
            this.transports = new HashSet<transport>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Nom de Societé")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        public string nomS { get; set; }


        [Display(Name = "Adresse")]
        [Required(ErrorMessage = "ce champs est obligatoire")]
        public string adresse { get; set; }
        public int id_client { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transport> transports { get; set; }
    }
}
